# Client threads configuration
clients:
    # Count of TCP connections
    count: 2
    # Initial count of concurrent connections
    fiber: 4
# Data source configuration
data: 
    # Signal filename
    # filename: testcls.wav
    # Available sizes for classification, ms
    duration: [750, 1000, 3000]
    # One cls packet size, ms 
    packet-size: 100
